### PR TITLE
Encrypted zprofile makefile fix

### PR DESCRIPTION
**Pull request by BShrivastav**
Current Changes include:

1. go-cty/cty - stable release from latest -> 1.9.1

-   Changes in developer/Makefile.
-   Changes in the Readme.md

2. Sample configuration for z profile - w/o a provisioner.
3. Sample configuration for encrypted-centos.
4. Checks for resource availability.

### CODE REVIEW

**Comment by juanpinzon** [comment]
Could you please make sure all the checks pass. Also the variables.pkvars.hcl shows `This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.`

**Comment by juanpinzon** [comment]
Please fix issues 
Screen Shot 2022-09-22 at 11 52 44 AM
Screen Shot 2022-09-22 at 11 51 32 AM

**Comment by BShrivastav** [comment]
@juanpinzon working on it.

**Comment by BShrivastav** [comment]
Will be creating a newer PR.

**Pull request closed without merging**
